import fs from "node:fs";
import path from "node:path";
import { loadConfig } from "./config.js";
import { ensureHome, resolvePaths } from "./paths.js";

export interface IntegrationRow {
  id: string;
  status: "available";
  target: string;
  mode: string;
}

export function integrationListRows(): IntegrationRow[] {
  return [
    {
      id: "codex",
      status: "available",
      target: "Codex CLI custom OpenAI-compatible provider",
      mode: "manual config snippet"
    }
  ];
}

export function formatIntegrationList(rows: IntegrationRow[]): string {
  return rows.map((row) => `${row.id}\tstatus=${row.status}\ttarget=${row.target}\tmode=${row.mode}`).join("\n");
}

export function applyIntegration(id: string, options: { dryRun?: boolean } = {}): Record<string, unknown> {
  if (id !== "codex") throw new Error(`Unknown integration: ${id}`);
  const artifact = codexIntegrationArtifact();
  if (!options.dryRun) {
    fs.mkdirSync(path.dirname(artifact.path), { recursive: true, mode: 0o700 });
    fs.writeFileSync(artifact.path, artifact.content, { mode: 0o600 });
  }
  return {
    integration: id,
    dry_run: options.dryRun === true,
    path: artifact.path,
    base_url: artifact.baseUrl,
    model: "steadyroute:auto",
    env_key: "STEADYROUTE_LOCAL_KEY",
    wire_api: "responses",
    command: artifact.command,
    config_flags: artifact.configFlags,
    wrote_file: options.dryRun === true ? false : true
  };
}

export function rollbackIntegration(id: string): Record<string, unknown> {
  if (id !== "codex") throw new Error(`Unknown integration: ${id}`);
  const artifact = codexIntegrationArtifact();
  const existed = fs.existsSync(artifact.path);
  if (existed) fs.rmSync(artifact.path, { force: true });
  return {
    integration: id,
    path: artifact.path,
    removed: existed
  };
}

export function formatIntegrationApply(result: Record<string, unknown>): string {
  const flags = Array.isArray(result.config_flags) ? result.config_flags as string[] : [];
  return [
    `Integration: ${result.integration}`,
    `Dry run: ${result.dry_run}`,
    `Artifact: ${result.path}`,
    `Base URL: ${result.base_url}`,
    `Model: ${result.model}`,
    `Wire API: ${result.wire_api}`,
    `Env key: ${result.env_key}`,
    "",
    "Codex config flags:",
    ...flags.map((flag) => `  ${flag}`),
    "",
    "Example:",
    String(result.command)
  ].join("\n");
}

export function formatIntegrationRollback(result: Record<string, unknown>): string {
  return `Integration: ${result.integration}\nArtifact: ${result.path}\nRemoved: ${result.removed}`;
}

function codexIntegrationArtifact(): { path: string; content: string; baseUrl: string; configFlags: string[]; command: string } {
  const paths = ensureHome(resolvePaths());
  const config = loadConfig();
  const baseUrl = `http://${config.host}:${config.port}/v1`;
  const configFlags = [
    '-c \'model="steadyroute:auto"\'',
    '-c \'model_provider="steadyroute"\'',
    '-c \'model_providers.steadyroute.name="SteadyRoute Local"\'',
    `-c 'model_providers.steadyroute.base_url="${baseUrl}"'`,
    '-c \'model_providers.steadyroute.wire_api="responses"\'',
    '-c \'model_providers.steadyroute.env_key="STEADYROUTE_LOCAL_KEY"\''
  ];
  const command = [
    "STEADYROUTE_LOCAL_KEY=steadyroute-local \\",
    "codex exec \\",
    "  --cd \"$DOGFOOD_PROJECT\" \\",
    "  --sandbox workspace-write \\",
    "  --ask-for-approval never \\",
    ...configFlags.map((flag) => `  ${flag} \\`),
    "  '<task prompt>'"
  ].join("\n");
  const content = [
    "# SteadyRoute Codex Integration",
    "",
    "This file is generated by `steadyroute integrations apply codex`.",
    "It does not modify Codex global configuration. Use the flags below when running Codex.",
    "",
    `Base URL: ${baseUrl}`,
    "Model: steadyroute:auto",
    "Wire API: responses",
    "Env key: STEADYROUTE_LOCAL_KEY",
    "",
    "Config flags:",
    ...configFlags.map((flag) => `- ${flag}`),
    "",
    "Example:",
    "```bash",
    command,
    "```",
    ""
  ].join("\n");
  return {
    path: path.join(paths.home, "integrations", "codex.md"),
    content,
    baseUrl,
    configFlags,
    command
  };
}
